## dataframe introduction
1. dataFrame()
2. haterogeneous
3. ordered
4. mutable , size mutable
5. duplication allowed
6. 2d datastructure of pandas
7. row and colums

In [1]:
import pandas as pd

In [3]:
df=pd.DataFrame()
type(df)

pandas.core.frame.DataFrame

In [10]:
df=pd.DataFrame([[101,'rohan',45000],[102,'karna',10000],[103,'parth','50000']] , columns = ['id','name','sal'])
df

    id   name    sal
0  101  roahn  45000
1  102  karna  10000
2  103  parth  50000

In [11]:
df['id']

0    101
1    102
2    103
Name: id, dtype: int64

In [18]:
df3 =  df.set_index('id')
df3

      name    sal
id
101  roahn  45000
102  karna  10000
103  parth  50000

In [19]:
df3

      name    sal
id
101  roahn  45000
102  karna  10000
103  parth  50000

In [22]:
df3.loc[101:102]

      name    sal
id
101  roahn  45000
102  karna  10000

In [21]:
df3.iloc[0:2]

      name    sal
id
101  roahn  45000
102  karna  10000

In [15]:
df2=pd.DataFrame({'id':[101,102,103],
                'name':['rohan','karan','parth'],
                  'sal':[10000,20000,30000]})
df2

    id   name    sal
0  101  rohan  10000
1  102  karan  20000
2  103  parth  30000

In [23]:
iris=pd.read_csv("C:/Users/Monali/OneDrive/Desktop/FBS/Data analysis/datasets/Iris.csv")
iris

     Sepal_Length  Sepal_Width  Petal_Length  Petal_Width    Species
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [24]:
iris.head()

   Sepal_Length  Sepal_Width  Petal_Length  Petal_Width Species
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [25]:
iris.tail()

     Sepal_Length  Sepal_Width  Petal_Length  Petal_Width    Species
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

In [27]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Sepal_Length  150 non-null    float64
 1   Sepal_Width   150 non-null    float64
 2   Petal_Length  150 non-null    float64
 3   Petal_Width   150 non-null    float64
 4   Species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [26]:
iris.describe()

       Sepal_Length  Sepal_Width  Petal_Length  Petal_Width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [29]:
iris['Sepal_Length'].mean()

np.float64(5.843333333333334)

In [30]:
iris['Sepal_Length'].agg(['mean','max','min','sum'])

mean      5.843333
max       7.900000
min       4.300000
sum     876.500000
Name: Sepal_Length, dtype: float64

In [31]:
iris['Sepal_Length'].unique()

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.4, 4.8, 4.3, 5.8, 5.7, 5.2, 5.5,
       4.5, 5.3, 7. , 6.4, 6.9, 6.5, 6.3, 6.6, 5.9, 6. , 6.1, 5.6, 6.7,
       6.2, 6.8, 7.1, 7.6, 7.3, 7.2, 7.7, 7.4, 7.9])

In [33]:
iris['Species'].value_counts()

Species
Setosa        50
Versicolor    50
Virginica     50
Name: count, dtype: int64

In [34]:
iris.drop('Species',axis=1,inplace=True)

In [35]:
iris.head()

   Sepal_Length  Sepal_Width  Petal_Length  Petal_Width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [36]:
iris.drop(0,inplace=True)

In [37]:
iris.head()

   Sepal_Length  Sepal_Width  Petal_Length  Petal_Width
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2
5           5.4          3.9           1.7          0.4

In [39]:
df['Address']=['pune','Mumbia','Delhi']
df

    id   name    sal Address
0  101  roahn  45000    pune
1  102  karna  10000  Mumbia
2  103  parth  50000   Delhi

In [ ]:
df.loc[3]=[104,'Abhinandam','800','']